apiVersion: apps/v1
kind: Deployment
metadata:
  name: cs-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cs-agent
  template:
    metadata:
      labels:
        app: cs-agent
    spec:
      containers:
      - name: cs-agent
        imagePullPolicy: IfNotPresent
        image: us-central1-docker.pkg.dev/gke-hackathon-472001/bank-of-anthos-gke/cs-agent:latest
        resources:
          limits:
            memory: "1Gi"
            cpu: "500m"
            ephemeral-storage: "1Gi"
          requests:
            memory: "512Mi"
            cpu: "100m"
            ephemeral-storage: "512Mi"
        ports:
        - containerPort: 8080
        env:
          - name: PORT
            value: "8080"
          - name: GOOGLE_CLOUD_PROJECT
            value: $GOOGLE_CLOUD_PROJECT
          - name: GOOGLE_CLOUD_LOCATION
            value: $GOOGLE_CLOUD_LOCATION
          - name: GOOGLE_GENAI_USE_VERTEXAI
            value: "$GOOGLE_GENAI_USE_VERTEXAI"
          - name: GOOGLE_API_KEY
            value: $GOOGLE_API_KEY
          # If using AI Studio, set GOOGLE_GENAI_USE_VERTEXAI to false and set the following:
          # - name: GOOGLE_API_KEY
          #   value: $GOOGLE_API_KEY
          # Add any other necessary environment variables your agent might need
---
apiVersion: v1
kind: Service
metadata:
  name: cs-agent
spec:       
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: cs-agent