apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats-subscriber
  labels:
    app: nats-subscriber
    application: bank-of-anthos
    team: messaging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nats-subscriber
  template:
    metadata:
      labels:
        app: nats-subscriber
        application: bank-of-anthos
        team: messaging
    spec:
      containers:
      - name: nats-subscriber
        image: us-central1-docker.pkg.dev/gke-hackathon-472001/bank-of-anthos-gke/nats-subscriber:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: NATS_URL
          value: "nats://simple-nats:4222"
        - name: NATS_SUBJECT
          value: "msg.transaction"
        - name: LOG_LEVEL
          value: "INFO"
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "64Mi"
            cpu: "100m"
      restartPolicy: Always
      serviceAccount: default
